### ISSUE TITLE
Image preview close button invisible

### ISSUE THREAD

**Issue by stonecrusher** [RaitaroH/DuckDuckGo-DeepDark#7]
See screenshot:
![2019-03-06](https://user-images.githubusercontent.com/1388389/53871039-b2c35e00-3ffb-11e9-8bfc-775452a0c98c.png)
DuckDuckGo-DeepDark version 1.8.7

**Comment by RaitaroH** [comment]
Thanks for poitint that out. Is fixed.

**Comment by RaitaroH** [comment]
BTW, I have also changed the way the theme works. You can now easily change color palettes.
